#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of a RedHat cluster Manager cluster using clustat
# N.B. This script needs to be run with SUDO by the nagios user

if [ ! -x /usr/sbin/clustat ] ; then
   echo "Cannot execute clustat - is it installed?"
   exit 3
fi

# Get the action first
if [ "$1" == "service" ] ; then

   # Perform a service check
   service=$2

   # check for empty service
   if [ "$service" == "" ] ; then
      echo "No service given to check?"
      exit 3
   fi

   if [ `/usr/sbin/clustat -s $service | grep -c started | awk '{print $1}'` -ne 1 ] ; then
      echo "clustat reports service $service not started"
      exit 1
   else
      echo "clustat reports service $service is started"
      exit 0
   fi

elif [ "$1" == "member" ] ; then
   
   # Perform a member check
   member=$2

   # check for empty member
   if [ "$member" == "" ] ; then
      echo "No member given to check?"
      exit 3
   fi

   if [ `/usr/sbin/clustat -m $member | grep -c Online | awk '{print $1}'` -ne 1 ] ; then
      echo "clustat reports member $member not Online"
      exit 1
   else
      echo "clustat reports member $member is Online"
      exit 0
   fi

else

   echo "No action to perform?"
   exit 3

fi

# Should never reach this point in the script - raise a fault

echo "Monitoring fault - check plugin"
exit 3
