#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check temperature reported by ganglia

# Inlet temperature thresholds
lowalert=35
highalert=40

nodename=$1

# check nodename is set or abort
if [ "$nodename" == "" ] ; then
   echo "No node name passed"
   exit 3
fi

# Use host resolution to work out what ganglia will know the node as
fullnodename=`gethostip $nodename 2> /dev/null | awk '{print $1}'`
gangliacluster=`gstat | grep Name | awk '{print $2}'`
RRDfile=/var/lib/ganglia/rrds/$gangliacluster/$fullnodename/InletTemp.rrd

# check we have ganglia data for this node
if [ ! -f $RRDfile ] ; then
   # really we should exit 3 here, but choose to exit 0 instead to avoid false alerts
   echo "No temperature data stored in ganglia for $nodename"
   # exit 3
   exit 0
fi

# get the last update stored by ganglia in the last hour
scinot=`rrdtool fetch $RRDfile AVERAGE -s e-1h | grep -v nan | tail -1 | awk '{print $2}'`

if [ "$scinot" == "" ] ; then
   echo "No temperature data stored in ganglia for $nodename"
   # exit 3
   exit 0
fi

# convert result to a decimal number
decval=`python -c "print float ('$scinot')" | cut -d. -f1`

# check if we have a value
if [ "$decval" == "" ] ; then
   echo "Could not retrieve temperature for $nodename"
   exit 0
fi

if [ $decval -ge $highalert ] ; then
   echo "Critical inlet temperature ($decval degrees C)"
   exit 2
elif [ $decval -ge $lowalert ] ; then
   echo "High inlet temperature ($decval degrees C)"
   exit 1
else
   echo "Normal inlet temperature ($decval degrees C)"
   exit 0
fi

# should not reach this point
exit 3

