#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check for node RAID faults via non-intrusive method
# Pass the node name as the first parameter

# set raid-check spool directory
checkdir=/var/spool/nagios/raid-check

# Check that raid output files are available
[[ -d $checkdir ]] || exit 3

# Check that we've been passed a parameter
remote=$1
if [ ! $remote ] ; then
   echo "No node name passed to check"
   exit 3
fi

# check we have output for this node
if [ ! -f $checkdir/$remote.raid.out ] || [ ! -s $checkdir/$remote.raid.out ] ; then
   echo "No log information found for $remote"
   exit 3
fi

# the command to run to check the service
checkcommand=`grep -ic Optimal $checkdir/$remote.raid.out | awk '{print $1}'`

if [ $checkcommand -lt 1 ] ; then
   # detected a disk fault
   echo "Detected non-optimal RAID status on $remote"
   exit 1
else
   # No faults found
   echo "RAID disk reports optimal on $remote"
   exit 0
fi

