#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check for processes on nodes not run via scheduler
#. /etc/profile.d/alces-profiles.sh > /dev/null 2>&1
#. /etc/profile.d/modules.sh > /dev/null 2>&1
#module -s load services/gridscheduler

export appdir=/opt/alces/pkg/services/gridscheduler/2011.11p1_155
export PATH=$PATH:${appdir}/bin/linux-x64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${appdir}/lib/linux-x64
export SGE_ROOT=${appdir}
export SGE_CELL=etc
export SGE_CLUSTER_NAME=cluster
export SGE_QMASTER_PORT=6444
export SGE_EXECD_PORT=6445
export SGE_CELL="etc"
export SGE_CLUSTER_NAME="cluster"
export SGE_EXECD_PORT="6445"
export SGE_QMASTER_PORT="6444"
export SGE_ROOT="/opt/alces/pkg/services/gridscheduler/2011.11p1_155"
PATH=$PATH:/opt/alces/pkg/services/gridscheduler/2011.11p1_155/bin/linux-x64/
qping=/opt/alces/pkg/services/gridscheduler/2011.11p1_155/bin/linux-x64/qping


minuser=500

target=$1
if [ "$target" == "" ] ; then
   echo "No target system provided"
   exit 3
fi

qhost=qhost

# Check monitor application is present and executable
[[ -x `which $qhost` ]] || exit 3

qmaster=`cat $appdir/etc/common/act_qmaster`

# first check the host process list for any owned by users

pslist=/tmp/ps.$target.out.$$
ssh $target ps -ef nh 2> /dev/null > $pslist 2>&1

if [ `wc -l $pslist | awk '{print $1}'` -eq 0 ] ; then
   echo "No information found for $target"
   rm -f $pslist
   exit 0
fi

totalprocs=`wc -l $pslist | grep -v "UID   PID  PPID  C STIME TTY" | awk '{print $1}'`

i=1
while [ $i -le $totalprocs ] ; do
   # if userID is higher than 500 then it's a user process
   uid=`head -$i $pslist | tail -n 1 | awk '{print $1}'`
   if [ $uid -ge $minuser ] ; then
      # found process running owned by high user ID
#      echo found process owned by $uid
      userlist=`echo -ne "$userlist\n \`head -$i $pslist | tail -n 1 | awk '{print $1}'\`" | sort | uniq`
   fi
   i=`expr $i + 1`
done

# now for each userid found, check if that user has a job running on the node
schedIDproc=`qstat -u \* -q *@$target | egrep -v "job-ID  prior   name|-------------------------" | awk '{print $4}' | sort | uniq`

for userIDnum in `echo $schedIDproc`
do
   numericid=`id -u $userIDnum`
   schedproc=`echo -e $schedproc $numericid`
done

#echo "Users with scheduled jobs: $schedproc"
#echo "Users with processes on node: $userlist"

badusers=""
# report any users running jobs which are not scheduled
for userid in `echo $userlist`
do
   # convert UID to username
   if [ `echo $schedproc | grep $userid | wc -l | awk '{print $1}'` -gt 0 ] ; then
#       echo User $userid has scheduled job correctly
       touch $pslist
   else
 #      echo User $userid is running on node without permission
       badusers=`echo -ne $badusers $userid`
   fi
done

if [ "$badusers" == "" ] ; then
   echo "All user processes on $target are scheduled"
   rm -f $pslist
   exit 0
else
   echo "Detected unscheduled user process on $target (UID=$badusers)"
   rm -f $pslist
   exit 1
fi

exit 3

