#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of a Qlogic 12300 switch via SSH
# N.B. This script needs to be run with SUDO by the nagios user

# Pass in the switch name as the first parameter

switchname=$1
sshkey=~nagios/.ssh/id_rsa
username=nagios

if [ "$switchname" == "" ] ; then
   echo "No IB switch name passed?"
   exit 3
fi 

checkcommand=`ssh -i $sshkey -l $username -o PasswordAuthentication=false $switchname hwcheck 2> /dev/null | head -1`

if [ `echo $checkcommand | grep -ic status | awk '{print $1}'` -lt 1 ] ; then
   echo "IB switch $switchname monitoring problem"
   exit 3
elif [ `echo $checkcommand | grep -ic status | awk '{print $1}'` -lt 1 ] ; then
   echo "IB switch $switchname `echo $checkcommand | cut -d' ' -f 2-`"
   exit 1
else  
   echo  "IB switch $switchname `echo $checkcommand | cut -d' ' -f 2-`"
   exit 0
fi

