#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the load of a client via ganglia

# Script expects hostname and load alarm percentage as parameters 1 and 2
target=$1
alarm=$2

if [ "$target" == "" ] ; then
   echo "No hostname provided to monitor"
   exit 3
fi

if [ "$alarm" == "" ] ; then
   alarm=150
fi

statusline=`gstat -a -1 | grep -i $target`
# format is:
# hostname                  CPUs   running       load1  load5  load15  $user  $system $idle $wio
# node01.my.cluster.local     8 (    6/  327) [  5.99,  5.86,  4.83] [  74.8,   0.0,   0.5,  24.7,   0.0] OFF

if [ "$statusline" == "" ] ; then
   echo "No data for $target available"
   exit 0
fi

numcpus=`echo $statusline | awk '{print $2}'`

if [ $numcpus -lt 2 ] ; then
   echo "Problem detecting CPU count on host $target"
   exit 3
fi

maxload=`expr $numcpus \* $alarm \/ 100`
currload=`echo $statusline | awk '{print $7}' | cut -d, -f1 | cut -d. -f1`

#echo maxload is $maxload currload is $currload numcpus is $numcpus

# report load
if [ $currload -le $maxload ] ; then
   echo "Load for $target is normal (`expr $currload \* 100 \/ $numcpus `%)"
   exit 0
else
   echo "Load warning for $target - `expr $currload \* 100 \/ $numcpus `% on $numcpus CPU host"
   exit 0
fi

exit 3

