#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of a NUT-managed UPS

upsname=$1

if [ "$upsname" == "" ] ; then
   echo "No UPS name passed"
   exit 3
fi

# the command to run to check the service
upsstatus=`/usr/bin/upsc $upsname | grep ups.status | awk '{print $2}'`

if [ ! -x /usr/bin/upsc ] ; then
   echo "No UPS monitor found - is NUT installed?"
   exit 3
fi

if [ "$upsstatus" == "OL" ] ; then
   echo "UPS reported online ($upsstatus)"
   exit 0
else 
   echo "UPS reported not online ($upsstatus)"
   exit 1
fi

# should not reach here
exit 3
