#Enable configuration of yum repos via pulp on symphony-repo (default:true)
symphonyrepo::yum::install_repoconfigs: true
#which symphony repos to enable
symphonyrepo::yum::enable_symphonyrepos:
 - epel
 - symphony
