#Client name string
symphonydirector::clientname: democlient
#RSA ssh key for root@director
symphonydirector::customization::directorkey: AAAAB3NzaC1yc2EAAAADAQABAAABAQC4R1TRug/xS6LBVRtSmABxAQL4e2jaeHyO8v0Hk6wOXwRkQ1GD2s4Tf/tmiM7b9r95n3pqMTiiZdYbdGKfielrdZobPXtc4kN6iGMvZXF8KoClMgHubKtbjeBGuE1lcvclza3vf+GTajPyIBU9r2bU9dLMT35uF41/dNbOCftvwU4RjYlHGKJEamvWN600kaHZg9LI70oulPACzIutNYrMIvi6MaqfBZYjYTEhoBZvqyi+5PgugwomHOqHD2UY8CaKYJk1WzDXp9ZoxlMUCfED9DWJNFxcs/MkSQNRmM7ekVSp71po7VtLePwdyIiAJtz5eKx8BwnC2Pq95ut8lhs1
#Install director ssh key to root
symphonydirector::customization::install_directorkey: true
#Enable syslog pushing
symphonydirector::customization::install_syslog: true

#TIME
#Enable ntp config
symphonydirector::time::install_ntp: true
#Add additional ntp servers (to os default)
#symphonydirector::time::additionalntpservers: 
# - '0.centos.pool.ntp.org'

#MAIL
#Enable postfix setup
symphonydirector::mail::install_postfix: true
#External mail relay for your domain
symphonydirector::mail::externalrelay: smtp.alces-software.com
#Internal mail domain to send mail as
symphonydirector::mail::maildomain: mgt.syphony.local
#Mail from address - this usually needs to be an email address your relay server will relay for
symphonydirector::mail::mailfrom: test@alces-software.com
---
#Enable configuration of yum repos via pulp on symphony-repo (default:true)
symphonyrepo::yum::install_repoconfigs: true
#which symphony repos to enable
symphonyrepo::yum::enable_symphonyrepos:
 - epel
 - symphony
#Client name string
symphonydirector::clientname: democlient
#RSA ssh key for root@director
symphonydirector::customization::directorkey: AAAAB3NzaC1yc2EAAAADAQABAAABAQC4R1TRug/xS6LBVRtSmABxAQL4e2jaeHyO8v0Hk6wOXwRkQ1GD2s4Tf/tmiM7b9r95n3pqMTiiZdYbdGKfielrdZobPXtc4kN6iGMvZXF8KoClMgHubKtbjeBGuE1lcvclza3vf+GTajPyIBU9r2bU9dLMT35uF41/dNbOCftvwU4RjYlHGKJEamvWN600kaHZg9LI70oulPACzIutNYrMIvi6MaqfBZYjYTEhoBZvqyi+5PgugwomHOqHD2UY8CaKYJk1WzDXp9ZoxlMUCfED9DWJNFxcs/MkSQNRmM7ekVSp71po7VtLePwdyIiAJtz5eKx8BwnC2Pq95ut8lhs1
#Install director ssh key to root
symphonydirector::customization::install_directorkey: true
#Enable syslog pushing
symphonydirector::customization::install_syslog: true

#TIME
#Enable ntp config
symphonydirector::time::install_ntp: true
#Add additional ntp servers (to os default)
#symphonydirector::time::additionalntpservers: 
# - '0.centos.pool.ntp.org'

#MAIL
#Enable postfix setup
symphonydirector::mail::install_postfix: true
#External mail relay for your domain
symphonydirector::mail::externalrelay: smtp.alces-software.com
#Internal mail domain to send mail as
symphonydirector::mail::maildomain: mgt.syphony.local
#Mail from address - this usually needs to be an email address your relay server will relay for
symphonydirector::mail::mailfrom: test@alces-software.com
