#Client name string
symphonydirector::clientname: fabian
#RSA ssh key for root@director
symphonydirector::customization::directorkey: AAAAB3NzaC1yc2EAAAADAQABAAABAQDPcoDb/FXvj1rp5F+5TONj1jbWFKe/U54SWKNyvAnJNpcNt64aB5zQwrOBcuYTYXSbN424+3jqAOK7F4yk6RDQoinuy0DAm8IX1pUnsRMBOz5qb9g7qhp5pvysWNJXvhhMnHuVipyAPz6gI7TJ7fghJcwWlJ7rtVZaggxf9ykW6chjmFq0XiWtVdRawfdVpec91uYJwxSJn+G9VJgiNuzybJJnXIYOHZvppTrvWDDHnBdHUrekVmRMOiMs2m0C9db/SHy6jCdPMZySyl0BXvaGw4slQWSa2o93XAuK5lpPmJWEdirJ+qldbHavtBzV1aS7p8Aptqdr/3yACpOHyqWR
#Install director ssh key to root
symphonydirector::customization::install_directorkey: true
#Enable syslog pushing
symphonydirector::customization::install_syslog: true

#TIME
#Enable ntp config
symphonydirector::time::install_ntp: true
#Add additional ntp servers (to os default)
#symphonydirector::time::additionalntpservers: 
# - '0.centos.pool.ntp.org'

#MAIL
#Enable postfix setup
symphonydirector::mail::install_postfix: true
#External mail relay for your domain
symphonydirector::mail::externalrelay: smtp.alces-software.com
#Internal mail domain to send mail as
symphonydirector::mail::maildomain: mgt.symphony.local
#Mail from address - this usually needs to be an email address your relay server will relay for
symphonydirector::mail::mailfrom: test@alces-software.com
#Symphony APP NFS mounts
symphony::nfsimports:
 'symphony-app.mgt.symphony.local:/opt/gridware':
   target: '/opt/gridware'
   options: intr,rsize=32768,wsize=32768,_netdev
# 'storage1.prv.<CLUSTERNAME>.compute.estate:/export/apps':
#   target: '/opt/apps'
#   options: intr,rsize=32768,wsize=32768,_netdev
# 'storage1.prv.<CLUSTERNAME>.compute.estate:/export/users':
#   target: '/users'
#   options: intr,rsize=32768,wsize=32768,_netdev
#Enable configuration of yum repos via pulp on symphony-repo (default:true)
symphonyrepo::yum::install_repoconfigs: true
#which symphony repos to enable
symphonyrepo::yum::enable_symphonyrepos:
 - epel
 - symphony
#Enable install/config of ganglia (default:true)
symphonymonitor::ganglia::install_ganglia: true
#Enable install/config of nagios (default:true)
symphonymonitor::nagios::install_nagios: true
